"""
decision tree test
"""

import pandas as pd
from decision_tree import DecisionTreeClassifier
from viz_tree import plot_tree
import matplotlib.pyplot as plt
from pathlib import Path

def test_dt_classification():
	# Load iris train/test CSV generated by iris_download.py
	data_dir = Path(__file__).parent / 'dataset'
	train_path = data_dir / 'iris_train.csv'
	test_path = data_dir / 'iris_test.csv'

	if not train_path.exists() or not test_path.exists():
		raise FileNotFoundError("iris_train.csv / iris_test.csv not found. Run iris_download.py first.")

	df_train = pd.read_csv(train_path)
	df_test = pd.read_csv(test_path)

	feature_names = list(df_train.columns[:-1])
	X = df_train[feature_names].to_numpy(dtype=float)
	y = df_train['label'].to_numpy(dtype=int)
	X_test = df_test[feature_names].to_numpy(dtype=float)
	y_test = df_test['label'].to_numpy(dtype=int)

	criteria = ["info_gain", "info_gain_ratio", "gini", "error_rate"]
	# Expect relatively high accuracy on iris (simple dataset). Threshold conservative.
	min_acc = 0.85

	for crit in criteria:
		print(f"\n=== Criterion: {crit} ===")
		dt_clf = DecisionTreeClassifier(criterion=crit, random_state=0)
		dt_clf.fit(X, y)
		preds = dt_clf.predict(X_test)
		acc = (preds == y_test).mean()
		print(f"Accuracy: {acc:.4f}")
		if acc < min_acc:
			raise AssertionError(f"Accuracy {acc:.4f} below threshold {min_acc} for criterion {crit}")
		fig, ax = plot_tree(dt_clf,
							 feat_names=feature_names,
							 class_names=["0", "1", "2"],
							 show_split_score=True,
							 show_leaf_samples=True,
							 top_padding=0.18)
		ax.set_title(f"Decision Tree ({crit}) acc={acc:.2f}")
		plt.savefig(f"output/iris_{crit}.png")


if __name__ == '__main__':
	test_dt_classification()
